name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - theme-stack   # branch chứa mã nguồn Hugo

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true   # để tải theme nếu dùng git submodule

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Build Hugo site (in subfolder my-site)
        working-directory: ./my-site
        run: hugo --minify -t hugo-theme-stack

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./my-site/public
